[package]
name = "rangular-macros"
description = "Proc macros for rangular component templates"
readme = "../../docs/README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false


[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
