[package]
name = "rangular-parser"
description = "Angular-subset HTML template parser for rangular"
readme = "../../docs/README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false


[dependencies]
rangular-expr = { workspace = true }
