[package]
name = "rangular-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
rangular-parser = { path = "../crates/rangular-parser" }

[[bin]]
name = "parse-html"
path = "fuzz_targets/parse_html.rs"
test = false
doc = false
bench = false
