[package]
name = "rangular-aot"
description = "Compile-time lowering of rangular templates to Leptos"
readme = "../../docs/README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish = false


[dependencies]
proc-macro2 = "1"
quote = "1"
rangular-expr = { workspace = true }
rangular-host = { workspace = true }
rangular-parser = { workspace = true }
send_wrapper = "0.6"

[dev-dependencies]
syn = { version = "2", features = ["full"] }
